language: cpp
dist:     trusty
sudo:     false

matrix:
  include:
  - os:  linux
    env: BITS=32
    addons:
      apt:
        packages:
        - g++-mingw-w64-i686
  - os:  linux
    env: BITS=64
    addons:
      apt:
        packages:
        - g++-mingw-w64-x86-64
script:
- make -f Makefile.mingw BITS=$BITS

deploy:
  provider:     releases
  file:         NppFTP*.zip
  file_glob:    true
  skip_cleanup: true
  api_key: $OAUTH_TOKEN
    
  on:
    tags: true
